package demos.springdata.springdataintro.dao;

import demos.springdata.springdataintro.model.User;
import org.springframework.data.jpa.repository.JpaRepository;


// The repository is generated by spring data
// It extends JpaRepository which extends CRUD repository which gives the basic CRUD operations
public interface UserRepository extends JpaRepository<User, Long> {
}
